import type { SeedNoun } from '@/types/database';

/**
 * v1 — Initial A1 noun vocabulary with inline categories.
 * Merged from the original a1-nouns.ts + nounCategoryMap.
 */
export const v1InitialNouns: SeedNoun[] = [
  // ── People & Family ──────────────────────────────────────────────────
  {
    german: 'Mann',
    article: 'der',
    plural: 'Männer',
    english: 'man',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Frau',
    article: 'die',
    plural: 'Frauen',
    english: 'woman',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Kind',
    article: 'das',
    plural: 'Kinder',
    english: 'child',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Junge',
    article: 'der',
    plural: 'Jungen',
    english: 'boy',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Mädchen',
    article: 'das',
    plural: 'Mädchen',
    english: 'girl',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Freund',
    article: 'der',
    plural: 'Freunde',
    english: 'friend (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Freundin',
    article: 'die',
    plural: 'Freundinnen',
    english: 'friend (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Bruder',
    article: 'der',
    plural: 'Brüder',
    english: 'brother',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Schwester',
    article: 'die',
    plural: 'Schwestern',
    english: 'sister',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Mutter',
    article: 'die',
    plural: 'Mütter',
    english: 'mother',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Vater',
    article: 'der',
    plural: 'Väter',
    english: 'father',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Baby',
    article: 'das',
    plural: 'Babys',
    english: 'baby',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Lehrer',
    article: 'der',
    plural: 'Lehrer',
    english: 'teacher (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Lehrerin',
    article: 'die',
    plural: 'Lehrerinnen',
    english: 'teacher (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Arzt',
    article: 'der',
    plural: 'Ärzte',
    english: 'doctor (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Ärztin',
    article: 'die',
    plural: 'Ärztinnen',
    english: 'doctor (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Nachbar',
    article: 'der',
    plural: 'Nachbarn',
    english: 'neighbour',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Familie',
    article: 'die',
    plural: 'Familien',
    english: 'family',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Eltern',
    article: 'die',
    plural: null,
    english: 'parents',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Großvater',
    article: 'der',
    plural: 'Großväter',
    english: 'grandfather',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Großmutter',
    article: 'die',
    plural: 'Großmütter',
    english: 'grandmother',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Sohn',
    article: 'der',
    plural: 'Söhne',
    english: 'son',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Tochter',
    article: 'die',
    plural: 'Töchter',
    english: 'daughter',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Mensch',
    article: 'der',
    plural: 'Menschen',
    english: 'person / human',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Kollege',
    article: 'der',
    plural: 'Kollegen',
    english: 'colleague (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Chef',
    article: 'der',
    plural: 'Chefs',
    english: 'boss',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Student',
    article: 'der',
    plural: 'Studenten',
    english: 'student (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Studentin',
    article: 'die',
    plural: 'Studentinnen',
    english: 'student (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Schüler',
    article: 'der',
    plural: 'Schüler',
    english: 'pupil (male)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Paar',
    article: 'das',
    plural: 'Paare',
    english: 'couple',
    level: 'A1',
    category: 'people',
  },

  // ── Animals ──────────────────────────────────────────────────────────
  {
    german: 'Hund',
    article: 'der',
    plural: 'Hunde',
    english: 'dog',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Katze',
    article: 'die',
    plural: 'Katzen',
    english: 'cat',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Vogel',
    article: 'der',
    plural: 'Vögel',
    english: 'bird',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Fisch',
    article: 'der',
    plural: 'Fische',
    english: 'fish',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Pferd',
    article: 'das',
    plural: 'Pferde',
    english: 'horse',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Maus',
    article: 'die',
    plural: 'Mäuse',
    english: 'mouse',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Kuh',
    article: 'die',
    plural: 'Kühe',
    english: 'cow',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Schwein',
    article: 'das',
    plural: 'Schweine',
    english: 'pig',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Huhn',
    article: 'das',
    plural: 'Hühner',
    english: 'chicken',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Bär',
    article: 'der',
    plural: 'Bären',
    english: 'bear',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Schaf',
    article: 'das',
    plural: 'Schafe',
    english: 'sheep',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Tier',
    article: 'das',
    plural: 'Tiere',
    english: 'animal',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Kaninchen',
    article: 'das',
    plural: 'Kaninchen',
    english: 'rabbit',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Schmetterling',
    article: 'der',
    plural: 'Schmetterlinge',
    english: 'butterfly',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Elefant',
    article: 'der',
    plural: 'Elefanten',
    english: 'elephant',
    level: 'A1',
    category: 'animals',
  },
  {
    german: 'Affe',
    article: 'der',
    plural: 'Affen',
    english: 'monkey',
    level: 'A1',
    category: 'animals',
  },

  // ── Home & Rooms ─────────────────────────────────────────────────────
  {
    german: 'Haus',
    article: 'das',
    plural: 'Häuser',
    english: 'house',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Wohnung',
    article: 'die',
    plural: 'Wohnungen',
    english: 'apartment',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Zimmer',
    article: 'das',
    plural: 'Zimmer',
    english: 'room',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Küche',
    article: 'die',
    plural: 'Küchen',
    english: 'kitchen',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Bad',
    article: 'das',
    plural: 'Bäder',
    english: 'bathroom',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Schlafzimmer',
    article: 'das',
    plural: 'Schlafzimmer',
    english: 'bedroom',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Wohnzimmer',
    article: 'das',
    plural: 'Wohnzimmer',
    english: 'living room',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Tür',
    article: 'die',
    plural: 'Türen',
    english: 'door',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Fenster',
    article: 'das',
    plural: 'Fenster',
    english: 'window',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Wand',
    article: 'die',
    plural: 'Wände',
    english: 'wall',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Boden',
    article: 'der',
    plural: 'Böden',
    english: 'floor',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Dach',
    article: 'das',
    plural: 'Dächer',
    english: 'roof',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Treppe',
    article: 'die',
    plural: 'Treppen',
    english: 'stairs',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Garten',
    article: 'der',
    plural: 'Gärten',
    english: 'garden',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Balkon',
    article: 'der',
    plural: 'Balkone',
    english: 'balcony',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Garage',
    article: 'die',
    plural: 'Garagen',
    english: 'garage',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Keller',
    article: 'der',
    plural: 'Keller',
    english: 'basement',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Flur',
    article: 'der',
    plural: 'Flure',
    english: 'hallway',
    level: 'A1',
    category: 'home',
  },
  {
    german: 'Etage',
    article: 'die',
    plural: 'Etagen',
    english: 'floor / storey',
    level: 'A1',
    category: 'home',
  },

  // ── Furniture & Household Objects ────────────────────────────────────
  {
    german: 'Tisch',
    article: 'der',
    plural: 'Tische',
    english: 'table',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Stuhl',
    article: 'der',
    plural: 'Stühle',
    english: 'chair',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Bett',
    article: 'das',
    plural: 'Betten',
    english: 'bed',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Sofa',
    article: 'das',
    plural: 'Sofas',
    english: 'sofa',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Schrank',
    article: 'der',
    plural: 'Schränke',
    english: 'cupboard / wardrobe',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Regal',
    article: 'das',
    plural: 'Regale',
    english: 'shelf',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Spiegel',
    article: 'der',
    plural: 'Spiegel',
    english: 'mirror',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Lampe',
    article: 'die',
    plural: 'Lampen',
    english: 'lamp',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Uhr',
    article: 'die',
    plural: 'Uhren',
    english: 'clock / watch',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Bild',
    article: 'das',
    plural: 'Bilder',
    english: 'picture',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Schlüssel',
    article: 'der',
    plural: 'Schlüssel',
    english: 'key',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Telefon',
    article: 'das',
    plural: 'Telefone',
    english: 'telephone',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Tasche',
    article: 'die',
    plural: 'Taschen',
    english: 'bag',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Buch',
    article: 'das',
    plural: 'Bücher',
    english: 'book',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Zeitung',
    article: 'die',
    plural: 'Zeitungen',
    english: 'newspaper',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Brille',
    article: 'die',
    plural: 'Brillen',
    english: 'glasses',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Koffer',
    article: 'der',
    plural: 'Koffer',
    english: 'suitcase',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Teppich',
    article: 'der',
    plural: 'Teppiche',
    english: 'carpet',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Seife',
    article: 'die',
    plural: 'Seifen',
    english: 'soap',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Handtuch',
    article: 'das',
    plural: 'Handtücher',
    english: 'towel',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Regenschirm',
    article: 'der',
    plural: 'Regenschirme',
    english: 'umbrella',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Messer',
    article: 'das',
    plural: 'Messer',
    english: 'knife',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Gabel',
    article: 'die',
    plural: 'Gabeln',
    english: 'fork',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Löffel',
    article: 'der',
    plural: 'Löffel',
    english: 'spoon',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Teller',
    article: 'der',
    plural: 'Teller',
    english: 'plate',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Tasse',
    article: 'die',
    plural: 'Tassen',
    english: 'cup',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Glas',
    article: 'das',
    plural: 'Gläser',
    english: 'glass',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Flasche',
    article: 'die',
    plural: 'Flaschen',
    english: 'bottle',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Topf',
    article: 'der',
    plural: 'Töpfe',
    english: 'pot',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Kühlschrank',
    article: 'der',
    plural: 'Kühlschränke',
    english: 'refrigerator',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Waschmaschine',
    article: 'die',
    plural: 'Waschmaschinen',
    english: 'washing machine',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Computer',
    article: 'der',
    plural: 'Computer',
    english: 'computer',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Handy',
    article: 'das',
    plural: 'Handys',
    english: 'mobile phone',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Fernseher',
    article: 'der',
    plural: 'Fernseher',
    english: 'television',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Radio',
    article: 'das',
    plural: 'Radios',
    english: 'radio',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Kamera',
    article: 'die',
    plural: 'Kameras',
    english: 'camera',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Stift',
    article: 'der',
    plural: 'Stifte',
    english: 'pen / pencil',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Papier',
    article: 'das',
    plural: 'Papiere',
    english: 'paper',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Brief',
    article: 'der',
    plural: 'Briefe',
    english: 'letter',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Karte',
    article: 'die',
    plural: 'Karten',
    english: 'card / map',
    level: 'A1',
    category: 'furniture',
  },
  {
    german: 'Geschenk',
    article: 'das',
    plural: 'Geschenke',
    english: 'gift',
    level: 'A1',
    category: 'furniture',
  },

  // ── Food & Drink ─────────────────────────────────────────────────────
  {
    german: 'Wasser',
    article: 'das',
    plural: null,
    english: 'water',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Brot',
    article: 'das',
    plural: 'Brote',
    english: 'bread',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Milch',
    article: 'die',
    plural: null,
    english: 'milk',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Apfel',
    article: 'der',
    plural: 'Äpfel',
    english: 'apple',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Ei',
    article: 'das',
    plural: 'Eier',
    english: 'egg',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Kaffee',
    article: 'der',
    plural: null,
    english: 'coffee',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Tee',
    article: 'der',
    plural: 'Tees',
    english: 'tea',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Fleisch',
    article: 'das',
    plural: null,
    english: 'meat',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Kuchen',
    article: 'der',
    plural: 'Kuchen',
    english: 'cake',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Käse',
    article: 'der',
    plural: null,
    english: 'cheese',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Butter',
    article: 'die',
    plural: null,
    english: 'butter',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Reis',
    article: 'der',
    plural: null,
    english: 'rice',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Nudel',
    article: 'die',
    plural: 'Nudeln',
    english: 'noodle / pasta',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Suppe',
    article: 'die',
    plural: 'Suppen',
    english: 'soup',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Salat',
    article: 'der',
    plural: 'Salate',
    english: 'salad',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Kartoffel',
    article: 'die',
    plural: 'Kartoffeln',
    english: 'potato',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Tomate',
    article: 'die',
    plural: 'Tomaten',
    english: 'tomato',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Zwiebel',
    article: 'die',
    plural: 'Zwiebeln',
    english: 'onion',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Banane',
    article: 'die',
    plural: 'Bananen',
    english: 'banana',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Orange',
    article: 'die',
    plural: 'Orangen',
    english: 'orange',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Zucker',
    article: 'der',
    plural: null,
    english: 'sugar',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Salz',
    article: 'das',
    plural: null,
    english: 'salt',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Öl',
    article: 'das',
    plural: 'Öle',
    english: 'oil',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Saft',
    article: 'der',
    plural: 'Säfte',
    english: 'juice',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Bier',
    article: 'das',
    plural: 'Biere',
    english: 'beer',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Wein',
    article: 'der',
    plural: 'Weine',
    english: 'wine',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Schokolade',
    article: 'die',
    plural: 'Schokoladen',
    english: 'chocolate',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Eis',
    article: 'das',
    plural: null,
    english: 'ice cream / ice',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Obst',
    article: 'das',
    plural: null,
    english: 'fruit',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Gemüse',
    article: 'das',
    plural: null,
    english: 'vegetables',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Hähnchen',
    article: 'das',
    plural: 'Hähnchen',
    english: 'chicken (food)',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Wurst',
    article: 'die',
    plural: 'Würste',
    english: 'sausage',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Brötchen',
    article: 'das',
    plural: 'Brötchen',
    english: 'bread roll',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Mahlzeit',
    article: 'die',
    plural: 'Mahlzeiten',
    english: 'meal',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Frühstück',
    article: 'das',
    plural: null,
    english: 'breakfast',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Mittagessen',
    article: 'das',
    plural: null,
    english: 'lunch',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Abendessen',
    article: 'das',
    plural: null,
    english: 'dinner',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Getränk',
    article: 'das',
    plural: 'Getränke',
    english: 'drink / beverage',
    level: 'A1',
    category: 'food',
  },
  {
    german: 'Restaurant',
    article: 'das',
    plural: 'Restaurants',
    english: 'restaurant',
    level: 'A1',
    category: 'food',
  },

  // ── Body ─────────────────────────────────────────────────────────────
  {
    german: 'Kopf',
    article: 'der',
    plural: 'Köpfe',
    english: 'head',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Hand',
    article: 'die',
    plural: 'Hände',
    english: 'hand',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Auge',
    article: 'das',
    plural: 'Augen',
    english: 'eye',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Herz',
    article: 'das',
    plural: 'Herzen',
    english: 'heart',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Fuß',
    article: 'der',
    plural: 'Füße',
    english: 'foot',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Arm',
    article: 'der',
    plural: 'Arme',
    english: 'arm',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Bein',
    article: 'das',
    plural: 'Beine',
    english: 'leg',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Finger',
    article: 'der',
    plural: 'Finger',
    english: 'finger',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Nase',
    article: 'die',
    plural: 'Nasen',
    english: 'nose',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Mund',
    article: 'der',
    plural: 'Münder',
    english: 'mouth',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Ohr',
    article: 'das',
    plural: 'Ohren',
    english: 'ear',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Haar',
    article: 'das',
    plural: 'Haare',
    english: 'hair',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Zahn',
    article: 'der',
    plural: 'Zähne',
    english: 'tooth',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Rücken',
    article: 'der',
    plural: 'Rücken',
    english: 'back',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Bauch',
    article: 'der',
    plural: 'Bäuche',
    english: 'belly / stomach',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Gesicht',
    article: 'das',
    plural: 'Gesichter',
    english: 'face',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Hals',
    article: 'der',
    plural: 'Hälse',
    english: 'neck / throat',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Knie',
    article: 'das',
    plural: 'Knie',
    english: 'knee',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Schulter',
    article: 'die',
    plural: 'Schultern',
    english: 'shoulder',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Haut',
    article: 'die',
    plural: null,
    english: 'skin',
    level: 'A1',
    category: 'body',
  },

  // ── Clothing ─────────────────────────────────────────────────────────
  {
    german: 'Schuh',
    article: 'der',
    plural: 'Schuhe',
    english: 'shoe',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Hose',
    article: 'die',
    plural: 'Hosen',
    english: 'trousers',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Kleid',
    article: 'das',
    plural: 'Kleider',
    english: 'dress',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Hemd',
    article: 'das',
    plural: 'Hemden',
    english: 'shirt',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Jacke',
    article: 'die',
    plural: 'Jacken',
    english: 'jacket',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Mantel',
    article: 'der',
    plural: 'Mäntel',
    english: 'coat',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Hut',
    article: 'der',
    plural: 'Hüte',
    english: 'hat',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Rock',
    article: 'der',
    plural: 'Röcke',
    english: 'skirt',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Pullover',
    article: 'der',
    plural: 'Pullover',
    english: 'sweater',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Socke',
    article: 'die',
    plural: 'Socken',
    english: 'sock',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Mütze',
    article: 'die',
    plural: 'Mützen',
    english: 'cap / beanie',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Handschuh',
    article: 'der',
    plural: 'Handschuhe',
    english: 'glove',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Schal',
    article: 'der',
    plural: 'Schals',
    english: 'scarf',
    level: 'A1',
    category: 'clothing',
  },
  {
    german: 'Anzug',
    article: 'der',
    plural: 'Anzüge',
    english: 'suit',
    level: 'A1',
    category: 'clothing',
  },

  // ── Nature ───────────────────────────────────────────────────────────
  {
    german: 'Baum',
    article: 'der',
    plural: 'Bäume',
    english: 'tree',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Blume',
    article: 'die',
    plural: 'Blumen',
    english: 'flower',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Park',
    article: 'der',
    plural: 'Parks',
    english: 'park',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Land',
    article: 'das',
    plural: 'Länder',
    english: 'country',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Fluss',
    article: 'der',
    plural: 'Flüsse',
    english: 'river',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Berg',
    article: 'der',
    plural: 'Berge',
    english: 'mountain',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'See',
    article: 'der',
    plural: 'Seen',
    english: 'lake',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Meer',
    article: 'das',
    plural: 'Meere',
    english: 'sea / ocean',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Strand',
    article: 'der',
    plural: 'Strände',
    english: 'beach',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Wald',
    article: 'der',
    plural: 'Wälder',
    english: 'forest',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Feld',
    article: 'das',
    plural: 'Felder',
    english: 'field',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Insel',
    article: 'die',
    plural: 'Inseln',
    english: 'island',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Himmel',
    article: 'der',
    plural: null,
    english: 'sky / heaven',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Sonne',
    article: 'die',
    plural: null,
    english: 'sun',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Mond',
    article: 'der',
    plural: 'Monde',
    english: 'moon',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Stern',
    article: 'der',
    plural: 'Sterne',
    english: 'star',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Erde',
    article: 'die',
    plural: null,
    english: 'earth / ground',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Luft',
    article: 'die',
    plural: null,
    english: 'air',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Feuer',
    article: 'das',
    plural: 'Feuer',
    english: 'fire',
    level: 'A1',
    category: 'nature',
  },
  {
    german: 'Stein',
    article: 'der',
    plural: 'Steine',
    english: 'stone',
    level: 'A1',
    category: 'nature',
  },

  // ── Places & Buildings ───────────────────────────────────────────────
  {
    german: 'Stadt',
    article: 'die',
    plural: 'Städte',
    english: 'city',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Straße',
    article: 'die',
    plural: 'Straßen',
    english: 'street',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Schule',
    article: 'die',
    plural: 'Schulen',
    english: 'school',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Brücke',
    article: 'die',
    plural: 'Brücken',
    english: 'bridge',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Weg',
    article: 'der',
    plural: 'Wege',
    english: 'path / way',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Platz',
    article: 'der',
    plural: 'Plätze',
    english: 'place / square',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Kirche',
    article: 'die',
    plural: 'Kirchen',
    english: 'church',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Krankenhaus',
    article: 'das',
    plural: 'Krankenhäuser',
    english: 'hospital',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Bahnhof',
    article: 'der',
    plural: 'Bahnhöfe',
    english: 'train station',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Flughafen',
    article: 'der',
    plural: 'Flughäfen',
    english: 'airport',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Hotel',
    article: 'das',
    plural: 'Hotels',
    english: 'hotel',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Museum',
    article: 'das',
    plural: 'Museen',
    english: 'museum',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Bibliothek',
    article: 'die',
    plural: 'Bibliotheken',
    english: 'library',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Supermarkt',
    article: 'der',
    plural: 'Supermärkte',
    english: 'supermarket',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Markt',
    article: 'der',
    plural: 'Märkte',
    english: 'market',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Geschäft',
    article: 'das',
    plural: 'Geschäfte',
    english: 'shop / store',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Apotheke',
    article: 'die',
    plural: 'Apotheken',
    english: 'pharmacy',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Bank',
    article: 'die',
    plural: 'Banken',
    english: 'bank',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Post',
    article: 'die',
    plural: null,
    english: 'post office',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Polizei',
    article: 'die',
    plural: null,
    english: 'police',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Büro',
    article: 'das',
    plural: 'Büros',
    english: 'office',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Fabrik',
    article: 'die',
    plural: 'Fabriken',
    english: 'factory',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Theater',
    article: 'das',
    plural: 'Theater',
    english: 'theatre',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Kino',
    article: 'das',
    plural: 'Kinos',
    english: 'cinema',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Universität',
    article: 'die',
    plural: 'Universitäten',
    english: 'university',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Kindergarten',
    article: 'der',
    plural: 'Kindergärten',
    english: 'kindergarten',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Rathaus',
    article: 'das',
    plural: 'Rathäuser',
    english: 'town hall',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Schloss',
    article: 'das',
    plural: 'Schlösser',
    english: 'castle / palace',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Café',
    article: 'das',
    plural: 'Cafés',
    english: 'café',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Bäckerei',
    article: 'die',
    plural: 'Bäckereien',
    english: 'bakery',
    level: 'A1',
    category: 'places',
  },

  // ── Transportation ───────────────────────────────────────────────────
  {
    german: 'Auto',
    article: 'das',
    plural: 'Autos',
    english: 'car',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Zug',
    article: 'der',
    plural: 'Züge',
    english: 'train',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Fahrrad',
    article: 'das',
    plural: 'Fahrräder',
    english: 'bicycle',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Bus',
    article: 'der',
    plural: 'Busse',
    english: 'bus',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Flugzeug',
    article: 'das',
    plural: 'Flugzeuge',
    english: 'aeroplane',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Schiff',
    article: 'das',
    plural: 'Schiffe',
    english: 'ship',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Straßenbahn',
    article: 'die',
    plural: 'Straßenbahnen',
    english: 'tram',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Taxi',
    article: 'das',
    plural: 'Taxis',
    english: 'taxi',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Motorrad',
    article: 'das',
    plural: 'Motorräder',
    english: 'motorcycle',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Boot',
    article: 'das',
    plural: 'Boote',
    english: 'boat',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Haltestelle',
    article: 'die',
    plural: 'Haltestellen',
    english: 'bus / tram stop',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Fahrkarte',
    article: 'die',
    plural: 'Fahrkarten',
    english: 'ticket (transport)',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Führerschein',
    article: 'der',
    plural: 'Führerscheine',
    english: 'driving licence',
    level: 'A1',
    category: 'transportation',
  },

  // ── Time & Calendar ──────────────────────────────────────────────────
  {
    german: 'Tag',
    article: 'der',
    plural: 'Tage',
    english: 'day',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Nacht',
    article: 'die',
    plural: 'Nächte',
    english: 'night',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Jahr',
    article: 'das',
    plural: 'Jahre',
    english: 'year',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Woche',
    article: 'die',
    plural: 'Wochen',
    english: 'week',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Monat',
    article: 'der',
    plural: 'Monate',
    english: 'month',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Stunde',
    article: 'die',
    plural: 'Stunden',
    english: 'hour',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Minute',
    article: 'die',
    plural: 'Minuten',
    english: 'minute',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Morgen',
    article: 'der',
    plural: 'Morgen',
    english: 'morning',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Abend',
    article: 'der',
    plural: 'Abende',
    english: 'evening',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Mittag',
    article: 'der',
    plural: 'Mittage',
    english: 'noon',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Wochenende',
    article: 'das',
    plural: 'Wochenenden',
    english: 'weekend',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Uhrzeit',
    article: 'die',
    plural: 'Uhrzeiten',
    english: 'time (of day)',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Geburtstag',
    article: 'der',
    plural: 'Geburtstage',
    english: 'birthday',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Feiertag',
    article: 'der',
    plural: 'Feiertage',
    english: 'holiday',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Termin',
    article: 'der',
    plural: 'Termine',
    english: 'appointment',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Urlaub',
    article: 'der',
    plural: 'Urlaube',
    english: 'vacation',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Anfang',
    article: 'der',
    plural: 'Anfänge',
    english: 'beginning',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Ende',
    article: 'das',
    plural: 'Enden',
    english: 'end',
    level: 'A1',
    category: 'time',
  },

  // ── Weather ──────────────────────────────────────────────────────────
  {
    german: 'Wetter',
    article: 'das',
    plural: null,
    english: 'weather',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Regen',
    article: 'der',
    plural: null,
    english: 'rain',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Schnee',
    article: 'der',
    plural: null,
    english: 'snow',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Wind',
    article: 'der',
    plural: 'Winde',
    english: 'wind',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Wolke',
    article: 'die',
    plural: 'Wolken',
    english: 'cloud',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Gewitter',
    article: 'das',
    plural: 'Gewitter',
    english: 'thunderstorm',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Nebel',
    article: 'der',
    plural: null,
    english: 'fog',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Temperatur',
    article: 'die',
    plural: 'Temperaturen',
    english: 'temperature',
    level: 'A1',
    category: 'weather',
  },
  {
    german: 'Grad',
    article: 'der',
    plural: 'Grad',
    english: 'degree',
    level: 'A1',
    category: 'weather',
  },

  // ── Work & Education ─────────────────────────────────────────────────
  {
    german: 'Arbeit',
    article: 'die',
    plural: 'Arbeiten',
    english: 'work',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Beruf',
    article: 'der',
    plural: 'Berufe',
    english: 'profession',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Firma',
    article: 'die',
    plural: 'Firmen',
    english: 'company',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Aufgabe',
    article: 'die',
    plural: 'Aufgaben',
    english: 'task / homework',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Kurs',
    article: 'der',
    plural: 'Kurse',
    english: 'course',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Prüfung',
    article: 'die',
    plural: 'Prüfungen',
    english: 'exam',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Klasse',
    article: 'die',
    plural: 'Klassen',
    english: 'class / grade',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Unterricht',
    article: 'der',
    plural: null,
    english: 'lesson / class',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Hausaufgabe',
    article: 'die',
    plural: 'Hausaufgaben',
    english: 'homework',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Beispiel',
    article: 'das',
    plural: 'Beispiele',
    english: 'example',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Frage',
    article: 'die',
    plural: 'Fragen',
    english: 'question',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Antwort',
    article: 'die',
    plural: 'Antworten',
    english: 'answer',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Wort',
    article: 'das',
    plural: 'Wörter',
    english: 'word',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Satz',
    article: 'der',
    plural: 'Sätze',
    english: 'sentence',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Text',
    article: 'der',
    plural: 'Texte',
    english: 'text',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Sprache',
    article: 'die',
    plural: 'Sprachen',
    english: 'language',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Seite',
    article: 'die',
    plural: 'Seiten',
    english: 'page / side',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Übung',
    article: 'die',
    plural: 'Übungen',
    english: 'exercise',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Heft',
    article: 'das',
    plural: 'Hefte',
    english: 'notebook',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Tafel',
    article: 'die',
    plural: 'Tafeln',
    english: 'blackboard',
    level: 'A1',
    category: 'education',
  },

  // ── Money & Shopping ─────────────────────────────────────────────────
  {
    german: 'Geld',
    article: 'das',
    plural: null,
    english: 'money',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Preis',
    article: 'der',
    plural: 'Preise',
    english: 'price',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Euro',
    article: 'der',
    plural: 'Euro',
    english: 'euro',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Cent',
    article: 'der',
    plural: 'Cent',
    english: 'cent',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Rechnung',
    article: 'die',
    plural: 'Rechnungen',
    english: 'bill / invoice',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Kasse',
    article: 'die',
    plural: 'Kassen',
    english: 'cash register',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Angebot',
    article: 'das',
    plural: 'Angebote',
    english: 'offer / deal',
    level: 'A1',
    category: 'money',
  },

  // ── Communication & Feelings ─────────────────────────────────────────
  {
    german: 'Name',
    article: 'der',
    plural: 'Namen',
    english: 'name',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Nummer',
    article: 'die',
    plural: 'Nummern',
    english: 'number',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Adresse',
    article: 'die',
    plural: 'Adressen',
    english: 'address',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'E-Mail',
    article: 'die',
    plural: 'E-Mails',
    english: 'e-mail',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Nachricht',
    article: 'die',
    plural: 'Nachrichten',
    english: 'message / news',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Gespräch',
    article: 'das',
    plural: 'Gespräche',
    english: 'conversation',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Musik',
    article: 'die',
    plural: null,
    english: 'music',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Lied',
    article: 'das',
    plural: 'Lieder',
    english: 'song',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Film',
    article: 'der',
    plural: 'Filme',
    english: 'film / movie',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Foto',
    article: 'das',
    plural: 'Fotos',
    english: 'photo',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Spiel',
    article: 'das',
    plural: 'Spiele',
    english: 'game',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Sport',
    article: 'der',
    plural: null,
    english: 'sport',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Hobby',
    article: 'das',
    plural: 'Hobbys',
    english: 'hobby',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Reise',
    article: 'die',
    plural: 'Reisen',
    english: 'trip / journey',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Fest',
    article: 'das',
    plural: 'Feste',
    english: 'celebration / party',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Party',
    article: 'die',
    plural: 'Partys',
    english: 'party',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Spaß',
    article: 'der',
    plural: null,
    english: 'fun',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Freude',
    article: 'die',
    plural: 'Freuden',
    english: 'joy',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Angst',
    article: 'die',
    plural: 'Ängste',
    english: 'fear',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Liebe',
    article: 'die',
    plural: null,
    english: 'love',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Glück',
    article: 'das',
    plural: null,
    english: 'happiness / luck',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Problem',
    article: 'das',
    plural: 'Probleme',
    english: 'problem',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Hilfe',
    article: 'die',
    plural: null,
    english: 'help',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Idee',
    article: 'die',
    plural: 'Ideen',
    english: 'idea',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Grund',
    article: 'der',
    plural: 'Gründe',
    english: 'reason',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Meinung',
    article: 'die',
    plural: 'Meinungen',
    english: 'opinion',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Interesse',
    article: 'das',
    plural: 'Interessen',
    english: 'interest',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Wunsch',
    article: 'der',
    plural: 'Wünsche',
    english: 'wish',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Traum',
    article: 'der',
    plural: 'Träume',
    english: 'dream',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Ruhe',
    article: 'die',
    plural: null,
    english: 'quiet / peace',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Lärm',
    article: 'der',
    plural: null,
    english: 'noise',
    level: 'A1',
    category: 'communication',
  },

  // ── Health ───────────────────────────────────────────────────────────
  {
    german: 'Gesundheit',
    article: 'die',
    plural: null,
    english: 'health',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Krankheit',
    article: 'die',
    plural: 'Krankheiten',
    english: 'illness',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Schmerz',
    article: 'der',
    plural: 'Schmerzen',
    english: 'pain',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Medikament',
    article: 'das',
    plural: 'Medikamente',
    english: 'medicine / drug',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Fieber',
    article: 'das',
    plural: null,
    english: 'fever',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Erkältung',
    article: 'die',
    plural: 'Erkältungen',
    english: 'cold (illness)',
    level: 'A1',
    category: 'health',
  },

  // ── Colours ──────────────────────────────────────────────────────────
  {
    german: 'Farbe',
    article: 'die',
    plural: 'Farben',
    english: 'colour',
    level: 'A1',
    category: 'colors',
  },

  // ── General & Abstract ───────────────────────────────────────────────
  {
    german: 'Ding',
    article: 'das',
    plural: 'Dinge',
    english: 'thing',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Teil',
    article: 'der',
    plural: 'Teile',
    english: 'part',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Stück',
    article: 'das',
    plural: 'Stücke',
    english: 'piece',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Art',
    article: 'die',
    plural: 'Arten',
    english: 'kind / type',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Zahl',
    article: 'die',
    plural: 'Zahlen',
    english: 'number (maths)',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Gruppe',
    article: 'die',
    plural: 'Gruppen',
    english: 'group',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Leben',
    article: 'das',
    plural: 'Leben',
    english: 'life',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Geschichte',
    article: 'die',
    plural: 'Geschichten',
    english: 'story / history',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Erfahrung',
    article: 'die',
    plural: 'Erfahrungen',
    english: 'experience',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Regel',
    article: 'die',
    plural: 'Regeln',
    english: 'rule',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Chance',
    article: 'die',
    plural: 'Chancen',
    english: 'chance / opportunity',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Unterschied',
    article: 'der',
    plural: 'Unterschiede',
    english: 'difference',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Zukunft',
    article: 'die',
    plural: null,
    english: 'future',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Vergangenheit',
    article: 'die',
    plural: null,
    english: 'past',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Wahrheit',
    article: 'die',
    plural: 'Wahrheiten',
    english: 'truth',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Frieden',
    article: 'der',
    plural: null,
    english: 'peace',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Erfolg',
    article: 'der',
    plural: 'Erfolge',
    english: 'success',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Fehler',
    article: 'der',
    plural: 'Fehler',
    english: 'mistake',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Ziel',
    article: 'das',
    plural: 'Ziele',
    english: 'goal / destination',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Recht',
    article: 'das',
    plural: 'Rechte',
    english: 'right / law',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Situation',
    article: 'die',
    plural: 'Situationen',
    english: 'situation',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Bedeutung',
    article: 'die',
    plural: 'Bedeutungen',
    english: 'meaning',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Information',
    article: 'die',
    plural: 'Informationen',
    english: 'information',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Programm',
    article: 'das',
    plural: 'Programme',
    english: 'programme',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Zeichen',
    article: 'das',
    plural: 'Zeichen',
    english: 'sign / symbol',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Möglichkeit',
    article: 'die',
    plural: 'Möglichkeiten',
    english: 'possibility',
    level: 'A1',
    category: 'general',
  },
];
