import type { SeedNoun } from '@/types/database';

/**
 * Generated from CSV on 2026-02-12
 * Source: vocab-a1-9.csv
 * Total entries: 35
 */
export const vocabA19: SeedNoun[] = [
  {
    german: 'Führerausweis',
    article: 'der',
    plural: 'Führerausweise',
    english: 'driving license',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Ticket',
    article: 'das',
    plural: 'Tickets',
    english: 'ticket',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Amt',
    article: 'das',
    plural: 'Ämter',
    english: 'office',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Fahrt',
    article: 'die',
    plural: 'Fahrten',
    english: 'trip',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Gesuch',
    article: 'das',
    plural: 'Gesuche',
    english: 'application',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Pass',
    article: 'der',
    plural: 'Pässe',
    english: 'passport',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Automat',
    article: 'der',
    plural: 'Automaten',
    english: 'machine',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Zone',
    article: 'die',
    plural: 'Zonen',
    english: 'zone',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Schluss',
    article: 'der',
    plural: 'Schlüsse',
    english: 'end',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Bereich',
    article: 'der',
    plural: 'Bereiche',
    english: 'area',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Gebühr',
    article: 'die',
    plural: 'Gebühren',
    english: 'fee',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Sekretär',
    article: 'der',
    plural: 'Sekretäre',
    english: 'secretary',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Sekretärin',
    article: 'die',
    plural: 'Sekretärinnen',
    english: 'secretary',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Zigarette',
    article: 'die',
    plural: 'Zigaretten',
    english: 'cigarette',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Parkplatz',
    article: 'der',
    plural: 'Parkplätze',
    english: 'parking spot',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Gepäck',
    article: 'das',
    plural: 'Gepäck',
    english: 'luggage',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Person',
    article: 'die',
    plural: 'Personen',
    english: 'person',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Geburtsname',
    article: 'der',
    plural: 'Geburtsnamen',
    english: 'birth name',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Geschlecht',
    article: 'das',
    plural: 'Geschlechter',
    english: 'gender',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Ausländer',
    article: 'der',
    plural: 'Ausländer',
    english: 'foreigner',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Ausländerin',
    article: 'die',
    plural: 'Ausländerinnen',
    english: 'foreigner',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Angehörige',
    article: 'der',
    plural: 'Angehörigen',
    english: 'relative',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Sprachschule',
    article: 'die',
    plural: 'Sprachschulen',
    english: 'language school',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Auskunft',
    article: 'die',
    plural: 'Auskünfte',
    english: 'information',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Erlaubnis',
    article: 'die',
    plural: 'Erlaubnisse',
    english: 'permission',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Botschaft',
    article: 'die',
    plural: 'Botschaften',
    english: 'embassy',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Einladung',
    article: 'die',
    plural: 'Einladungen',
    english: 'invitation',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Dokument',
    article: 'das',
    plural: 'Dokumente',
    english: 'document',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Identitätskarte',
    article: 'die',
    plural: 'Identitätskarten',
    english: 'ID card',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Versicherung',
    article: 'die',
    plural: 'Versicherungen',
    english: 'insurance',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Visum',
    article: 'das',
    plural: 'Visa',
    english: 'visa',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Angestellte',
    article: 'der',
    plural: 'Angestellten',
    english: 'employee',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Besuch',
    article: 'der',
    plural: 'Besuche',
    english: 'visit',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Reservation',
    article: 'die',
    plural: 'Reservationen',
    english: 'reservation',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Flug',
    article: 'der',
    plural: 'Flüge',
    english: 'flight',
    level: 'A1',
    category: 'transportation',
  },
];
