import type { SeedNoun } from '@/types/database';

/**
 * Generated from CSV on 2026-02-12
 * Source: vocab-a1-8.csv
 * Total entries: 54
 */
export const vocabA18: SeedNoun[] = [
  {
    german: 'Spital',
    article: 'das',
    plural: 'Spitäler',
    english: 'hospital',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Interview',
    article: 'das',
    plural: 'Interviews',
    english: 'interview',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Fernsehen',
    article: 'das',
    plural: 'Fernsehen',
    english: 'television',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Ausbildung',
    article: 'die',
    plural: 'Ausbildungen',
    english: 'education',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Chefin',
    article: 'die',
    plural: 'Chefinnen',
    english: 'boss (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Patient',
    article: 'der',
    plural: 'Patienten',
    english: 'patient',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Patientin',
    article: 'die',
    plural: 'Patientinnen',
    english: 'patient (female)',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Hauswart',
    article: 'der',
    plural: 'Hauswarte',
    english: 'janitor',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Hauswartin',
    article: 'die',
    plural: 'Hauswartinnen',
    english: 'janitor (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Journalist',
    article: 'der',
    plural: 'Journalisten',
    english: 'journalist',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Journalistin',
    article: 'die',
    plural: 'Journalistinnen',
    english: 'journalist (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Thema',
    article: 'das',
    plural: 'Themen',
    english: 'topic',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Mechatroniker',
    article: 'der',
    plural: 'Mechatroniker',
    english: 'mechatronics engineer',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Mechatronikerin',
    article: 'die',
    plural: 'Mechatronikerinnen',
    english: 'mechatronics engineer (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Hausmann',
    article: 'der',
    plural: 'Hausmänner',
    english: 'househusband',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Hausfrau',
    article: 'die',
    plural: 'Hausfrauen',
    english: 'housewife',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Polizist',
    article: 'der',
    plural: 'Polizisten',
    english: 'police officer',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Polizistin',
    article: 'die',
    plural: 'Polizistinnen',
    english: 'police officer (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Pflegefachmann',
    article: 'der',
    plural: 'Pflegefachmänner',
    english: 'nurse',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Pflegefachfrau',
    article: 'die',
    plural: 'Pflegefachfrauen',
    english: 'nurse (female)',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Job',
    article: 'der',
    plural: 'Jobs',
    english: 'job',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Stelle',
    article: 'die',
    plural: 'Stellen',
    english: 'position',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Bewerbung',
    article: 'die',
    plural: 'Bewerbungen',
    english: 'application',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Praktikum',
    article: 'das',
    plural: 'Praktika',
    english: 'internship',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Abteilung',
    article: 'die',
    plural: 'Abteilungen',
    english: 'department',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Leiter',
    article: 'der',
    plural: 'Leiter',
    english: 'manager',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Leiterin',
    article: 'die',
    plural: 'Leiterinnen',
    english: 'manager (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Wirtschaft',
    article: 'die',
    plural: 'Wirtschaften',
    english: 'economy',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Abschluss',
    article: 'der',
    plural: 'Abschlüsse',
    english: 'degree',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Gruss',
    article: 'der',
    plural: 'Grüsse',
    english: 'greeting',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Reiseführer',
    article: 'der',
    plural: 'Reiseführer',
    english: 'tour guide',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Reiseführerin',
    article: 'die',
    plural: 'Reiseführerinnen',
    english: 'tour guide (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Tourist',
    article: 'der',
    plural: 'Touristen',
    english: 'tourist',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Touristin',
    article: 'die',
    plural: 'Touristinnen',
    english: 'tourist (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Berufserfahrung',
    article: 'die',
    plural: 'Berufserfahrungen',
    english: 'work experience',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Stress',
    article: 'der',
    plural: 'Stress',
    english: 'stress',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Kellner',
    article: 'der',
    plural: 'Kellner',
    english: 'waiter',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Kellnerin',
    article: 'die',
    plural: 'Kellnerinnen',
    english: 'waitress',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Architekt',
    article: 'der',
    plural: 'Architekten',
    english: 'architect',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Architektin',
    article: 'die',
    plural: 'Architektinnen',
    english: 'architect (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Koch',
    article: 'der',
    plural: 'Köche',
    english: 'cook',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Köchin',
    article: 'die',
    plural: 'Köchinnen',
    english: 'cook (female)',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Kollegin',
    article: 'die',
    plural: 'Kolleginnen',
    english: 'colleague (female)',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Ausland',
    article: 'das',
    plural: 'Ausland',
    english: 'foreign country',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Fahrer',
    article: 'der',
    plural: 'Fahrer',
    english: 'driver',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Fahrerin',
    article: 'die',
    plural: 'Fahrerinnen',
    english: 'driver (female)',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Vollzeit',
    article: 'die',
    plural: 'Vollzeit',
    english: 'full-time',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Teilzeit',
    article: 'die',
    plural: 'Teilzeit',
    english: 'part-time',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Nachhilfe',
    article: 'die',
    plural: 'Nachhilfe',
    english: 'tutoring',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Aushilfe',
    article: 'die',
    plural: 'Aushilfen',
    english: 'temporary help',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Lohn',
    article: 'der',
    plural: 'Löhne',
    english: 'wage',
    level: 'A1',
    category: 'money',
  },
  {
    german: 'Service',
    article: 'der',
    plural: 'Services',
    english: 'service',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Stellenanzeige',
    article: 'die',
    plural: 'Stellenanzeigen',
    english: 'job advertisement',
    level: 'A1',
    category: 'education',
  },
  {
    german: 'Nachfrage',
    article: 'die',
    plural: 'Nachfragen',
    english: 'inquiry',
    level: 'A1',
    category: 'general',
  },
];
