import type { SeedNoun } from '@/types/database';

/**
 * Generated from CSV on 2026-02-12
 * Source: vocab-a1-chapters-10-11.csv
 * Total entries: 28
 */
export const vocabA110: SeedNoun[] = [
  {
    german: 'Club',
    article: 'der',
    plural: 'Clubs',
    english: 'club',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Notfallstation',
    article: 'die',
    plural: 'Notfallstationen',
    english: 'emergency room',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Tablette',
    article: 'die',
    plural: 'Tabletten',
    english: 'tablet',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Unfall',
    article: 'der',
    plural: 'Unfälle',
    english: 'accident',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Doktor',
    article: 'der',
    plural: 'Doktoren',
    english: 'doctor',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Fuss',
    article: 'der',
    plural: 'Füsse',
    english: 'foot',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Brust',
    article: 'die',
    plural: 'Brüste',
    english: 'chest',
    level: 'A1',
    category: 'body',
  },
  {
    german: 'Kuss',
    article: 'der',
    plural: 'Küsse',
    english: 'kiss',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Bekannte',
    article: 'der',
    plural: 'Bekannten',
    english: 'acquaintance',
    level: 'A1',
    category: 'people',
  },
  {
    german: 'Schritt',
    article: 'der',
    plural: 'Schritte',
    english: 'step',
    level: 'A1',
    category: 'general',
  },
  {
    german: 'Husten',
    article: 'der',
    plural: 'Husten',
    english: 'cough',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Salbe',
    article: 'die',
    plural: 'Salben',
    english: 'ointment',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Schnupfen',
    article: 'der',
    plural: 'Schnupfen',
    english: 'cold',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Absender',
    article: 'der',
    plural: 'Absender',
    english: 'sender',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Empfänger',
    article: 'der',
    plural: 'Empfänger',
    english: 'recipient',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Anrede',
    article: 'die',
    plural: 'Anreden',
    english: 'salutation',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Datum',
    article: 'das',
    plural: 'Daten',
    english: 'date',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Unterschrift',
    article: 'die',
    plural: 'Unterschriften',
    english: 'signature',
    level: 'A1',
    category: 'communication',
  },
  {
    german: 'Sprechstunde',
    article: 'die',
    plural: 'Sprechstunden',
    english: 'office hours',
    level: 'A1',
    category: 'time',
  },
  {
    german: 'Krankenkassenkarte',
    article: 'die',
    plural: 'Krankenkassenkarten',
    english: 'health insurance card',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Notfallarzt',
    article: 'der',
    plural: 'Notfallärzte',
    english: 'emergency doctor',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Notfall',
    article: 'der',
    plural: 'Notfälle',
    english: 'emergency',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Sanität',
    article: 'die',
    plural: 'Sanitäten',
    english: 'ambulance service',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Notarzt',
    article: 'der',
    plural: 'Notärzte',
    english: 'emergency doctor',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Verletzung',
    article: 'die',
    plural: 'Verletzungen',
    english: 'injury',
    level: 'A1',
    category: 'health',
  },
  {
    german: 'Autogarage',
    article: 'die',
    plural: 'Autogaragen',
    english: 'car garage',
    level: 'A1',
    category: 'places',
  },
  {
    german: 'Autobahn',
    article: 'die',
    plural: 'Autobahnen',
    english: 'highway',
    level: 'A1',
    category: 'transportation',
  },
  {
    german: 'Metzgerei',
    article: 'die',
    plural: 'Metzgereien',
    english: 'butcher shop',
    level: 'A1',
    category: 'places',
  },
];
