import type { SeedCategory } from '@/types/database';

/**
 * Standard categories for German vocabulary.
 * Display order determines how they appear in category selectors.
 */
export const categories: SeedCategory[] = [
  { name: 'people', display_name: 'People & Family', display_order: 1 },
  { name: 'animals', display_name: 'Animals', display_order: 2 },
  { name: 'home', display_name: 'Home & Rooms', display_order: 3 },
  { name: 'furniture', display_name: 'Furniture & Objects', display_order: 4 },
  { name: 'food', display_name: 'Food & Drink', display_order: 5 },
  { name: 'body', display_name: 'Body Parts', display_order: 6 },
  { name: 'clothing', display_name: 'Clothing', display_order: 7 },
  { name: 'nature', display_name: 'Nature', display_order: 8 },
  { name: 'places', display_name: 'Places & Buildings', display_order: 9 },
  { name: 'transportation', display_name: 'Transportation', display_order: 10 },
  { name: 'time', display_name: 'Time & Calendar', display_order: 11 },
  { name: 'weather', display_name: 'Weather', display_order: 12 },
  { name: 'education', display_name: 'Education & Work', display_order: 13 },
  { name: 'money', display_name: 'Money & Shopping', display_order: 14 },
  {
    name: 'communication',
    display_name: 'Communication & Feelings',
    display_order: 15,
  },
  { name: 'health', display_name: 'Health', display_order: 16 },
  { name: 'colors', display_name: 'Colors', display_order: 17 },
  { name: 'general', display_name: 'General & Abstract', display_order: 18 },
];

/**
 * Map German nouns to category names.
 * Uses the 'german' field as the key for mapping during seed data migration.
 */
export const nounCategoryMap: Record<string, string> = {
  // People & Family
  Mann: 'people',
  Frau: 'people',
  Kind: 'people',
  Junge: 'people',
  Mädchen: 'people',
  Freund: 'people',
  Freundin: 'people',
  Bruder: 'people',
  Schwester: 'people',
  Mutter: 'people',
  Vater: 'people',
  Baby: 'people',
  Lehrer: 'people',
  Lehrerin: 'people',
  Arzt: 'people',
  Ärztin: 'people',
  Nachbar: 'people',
  Familie: 'people',
  Eltern: 'people',
  Großvater: 'people',
  Großmutter: 'people',
  Sohn: 'people',
  Tochter: 'people',
  Mensch: 'people',
  Kollege: 'people',
  Chef: 'people',
  Student: 'people',
  Studentin: 'people',
  Schüler: 'people',
  Paar: 'people',

  // Animals
  Hund: 'animals',
  Katze: 'animals',
  Vogel: 'animals',
  Fisch: 'animals',
  Pferd: 'animals',
  Maus: 'animals',
  Kuh: 'animals',
  Schwein: 'animals',
  Huhn: 'animals',
  Bär: 'animals',
  Schaf: 'animals',
  Tier: 'animals',
  Kaninchen: 'animals',
  Schmetterling: 'animals',
  Elefant: 'animals',
  Affe: 'animals',

  // Home & Rooms
  Haus: 'home',
  Wohnung: 'home',
  Zimmer: 'home',
  Küche: 'home',
  Bad: 'home',
  Schlafzimmer: 'home',
  Wohnzimmer: 'home',
  Tür: 'home',
  Fenster: 'home',
  Wand: 'home',
  Boden: 'home',
  Dach: 'home',
  Treppe: 'home',
  Garten: 'home',
  Balkon: 'home',
  Garage: 'home',
  Keller: 'home',
  Flur: 'home',
  Etage: 'home',

  // Furniture & Household Objects
  Tisch: 'furniture',
  Stuhl: 'furniture',
  Bett: 'furniture',
  Sofa: 'furniture',
  Schrank: 'furniture',
  Regal: 'furniture',
  Spiegel: 'furniture',
  Lampe: 'furniture',
  Uhr: 'furniture',
  Bild: 'furniture',
  Schlüssel: 'furniture',
  Telefon: 'furniture',
  Tasche: 'furniture',
  Buch: 'furniture',
  Zeitung: 'furniture',
  Brille: 'furniture',
  Koffer: 'furniture',
  Teppich: 'furniture',
  Seife: 'furniture',
  Handtuch: 'furniture',
  Regenschirm: 'furniture',
  Messer: 'furniture',
  Gabel: 'furniture',
  Löffel: 'furniture',
  Teller: 'furniture',
  Tasse: 'furniture',
  Glas: 'furniture',
  Flasche: 'furniture',
  Topf: 'furniture',
  Kühlschrank: 'furniture',
  Waschmaschine: 'furniture',
  Computer: 'furniture',
  Handy: 'furniture',
  Fernseher: 'furniture',
  Radio: 'furniture',
  Kamera: 'furniture',
  Stift: 'furniture',
  Papier: 'furniture',
  Brief: 'furniture',
  Karte: 'furniture',
  Geschenk: 'furniture',

  // Food & Drink
  Wasser: 'food',
  Brot: 'food',
  Milch: 'food',
  Apfel: 'food',
  Ei: 'food',
  Kaffee: 'food',
  Tee: 'food',
  Fleisch: 'food',
  Kuchen: 'food',
  Käse: 'food',
  Butter: 'food',
  Reis: 'food',
  Nudel: 'food',
  Suppe: 'food',
  Salat: 'food',
  Kartoffel: 'food',
  Tomate: 'food',
  Zwiebel: 'food',
  Banane: 'food',
  Orange: 'food',
  Zucker: 'food',
  Salz: 'food',
  Öl: 'food',
  Saft: 'food',
  Bier: 'food',
  Wein: 'food',
  Schokolade: 'food',
  Eis: 'food',
  Obst: 'food',
  Gemüse: 'food',
  Hähnchen: 'food',
  Wurst: 'food',
  Brötchen: 'food',
  Mahlzeit: 'food',
  Frühstück: 'food',
  Mittagessen: 'food',
  Abendessen: 'food',
  Getränk: 'food',
  Restaurant: 'food',

  // Body
  Kopf: 'body',
  Hand: 'body',
  Auge: 'body',
  Herz: 'body',
  Fuß: 'body',
  Arm: 'body',
  Bein: 'body',
  Finger: 'body',
  Nase: 'body',
  Mund: 'body',
  Ohr: 'body',
  Haar: 'body',
  Zahn: 'body',
  Rücken: 'body',
  Bauch: 'body',
  Gesicht: 'body',
  Hals: 'body',
  Knie: 'body',
  Schulter: 'body',
  Haut: 'body',

  // Clothing
  Schuh: 'clothing',
  Hose: 'clothing',
  Kleid: 'clothing',
  Hemd: 'clothing',
  Jacke: 'clothing',
  Mantel: 'clothing',
  Hut: 'clothing',
  Rock: 'clothing',
  Pullover: 'clothing',
  Socke: 'clothing',
  Mütze: 'clothing',
  Handschuh: 'clothing',
  Schal: 'clothing',
  Anzug: 'clothing',

  // Nature & Places
  Stadt: 'places',
  Straße: 'places',
  Schule: 'places',
  Land: 'nature',
  Baum: 'nature',
  Blume: 'nature',
  Park: 'nature',
  Fluss: 'nature',
  Berg: 'nature',
  See: 'nature',
  Meer: 'nature',
  Strand: 'nature',
  Wald: 'nature',
  Feld: 'nature',
  Insel: 'nature',
  Himmel: 'nature',
  Sonne: 'nature',
  Mond: 'nature',
  Stern: 'nature',
  Erde: 'nature',
  Luft: 'nature',
  Feuer: 'nature',
  Stein: 'nature',
  Brücke: 'places',
  Weg: 'places',
  Platz: 'places',

  // Buildings & Public Places
  Kirche: 'places',
  Krankenhaus: 'places',
  Bahnhof: 'places',
  Flughafen: 'places',
  Hotel: 'places',
  Museum: 'places',
  Bibliothek: 'places',
  Supermarkt: 'places',
  Markt: 'places',
  Geschäft: 'places',
  Apotheke: 'places',
  Bank: 'places',
  Post: 'places',
  Polizei: 'places',
  Büro: 'places',
  Fabrik: 'places',
  Theater: 'places',
  Kino: 'places',
  Universität: 'places',
  Kindergarten: 'places',
  Rathaus: 'places',
  Schloss: 'places',
  Café: 'places',
  Bäckerei: 'places',

  // Transportation
  Auto: 'transportation',
  Zug: 'transportation',
  Fahrrad: 'transportation',
  Bus: 'transportation',
  Flugzeug: 'transportation',
  Schiff: 'transportation',
  Straßenbahn: 'transportation',
  Taxi: 'transportation',
  Motorrad: 'transportation',
  Boot: 'transportation',
  Haltestelle: 'transportation',
  Fahrkarte: 'transportation',
  Führerschein: 'transportation',

  // Time & Calendar
  Tag: 'time',
  Nacht: 'time',
  Jahr: 'time',
  Woche: 'time',
  Monat: 'time',
  Stunde: 'time',
  Minute: 'time',
  Morgen: 'time',
  Abend: 'time',
  Mittag: 'time',
  Wochenende: 'time',
  Uhrzeit: 'time',
  Geburtstag: 'time',
  Feiertag: 'time',
  Termin: 'time',
  Urlaub: 'time',
  Anfang: 'time',
  Ende: 'time',

  // Weather
  Wetter: 'weather',
  Regen: 'weather',
  Schnee: 'weather',
  Wind: 'weather',
  Wolke: 'weather',
  Gewitter: 'weather',
  Nebel: 'weather',
  Temperatur: 'weather',
  Grad: 'weather',

  // Work & Education
  Arbeit: 'education',
  Beruf: 'education',
  Firma: 'education',
  Aufgabe: 'education',
  Kurs: 'education',
  Prüfung: 'education',
  Klasse: 'education',
  Unterricht: 'education',
  Hausaufgabe: 'education',
  Beispiel: 'education',
  Frage: 'education',
  Antwort: 'education',
  Wort: 'education',
  Satz: 'education',
  Text: 'education',
  Sprache: 'education',
  Seite: 'education',
  Übung: 'education',
  Heft: 'education',
  Tafel: 'education',

  // Money & Shopping
  Geld: 'money',
  Preis: 'money',
  Euro: 'money',
  Cent: 'money',
  Rechnung: 'money',
  Kasse: 'money',
  Angebot: 'money',

  // Communication & Feelings
  Name: 'communication',
  Nummer: 'communication',
  Adresse: 'communication',
  'E-Mail': 'communication',
  Nachricht: 'communication',
  Gespräch: 'communication',
  Musik: 'communication',
  Lied: 'communication',
  Film: 'communication',
  Foto: 'communication',
  Spiel: 'communication',
  Sport: 'communication',
  Hobby: 'communication',
  Reise: 'communication',
  Fest: 'communication',
  Party: 'communication',
  Spaß: 'communication',
  Freude: 'communication',
  Angst: 'communication',
  Liebe: 'communication',
  Glück: 'communication',
  Problem: 'communication',
  Hilfe: 'communication',
  Idee: 'communication',
  Grund: 'communication',
  Meinung: 'communication',
  Interesse: 'communication',
  Wunsch: 'communication',
  Traum: 'communication',
  Ruhe: 'communication',
  Lärm: 'communication',

  // Health
  Gesundheit: 'health',
  Krankheit: 'health',
  Schmerz: 'health',
  Medikament: 'health',
  Fieber: 'health',
  Erkältung: 'health',

  // Colours
  Farbe: 'colors',

  // General & Abstract
  Ding: 'general',
  Teil: 'general',
  Stück: 'general',
  Art: 'general',
  Zahl: 'general',
  Gruppe: 'general',
  Leben: 'general',
  Geschichte: 'general',
  Erfahrung: 'general',
  Regel: 'general',
  Chance: 'general',
  Unterschied: 'general',
  Zukunft: 'general',
  Vergangenheit: 'general',
  Wahrheit: 'general',
  Frieden: 'general',
  Erfolg: 'general',
  Fehler: 'general',
  Ziel: 'general',
  Recht: 'general',
  Situation: 'general',
  Bedeutung: 'general',
  Information: 'general',
  Programm: 'general',
  Zeichen: 'general',
  Möglichkeit: 'general',
};
