# fly.toml app configuration file generated for uben-pocketbase-backend on 2026-02-15T15:12:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uben-pocketbase-backend'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'pb_data'
  destination = '/pb/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
