import type { SeedVerb } from '@/types/database';

/**
 * A1/A2 verbs for the Präteritum (simple past) quiz feature.
 *
 * `past_tense` is the 3rd person singular Präteritum form (e.g. "ging" for
 * "gehen", "war" for "sein") — this is memorized vocabulary for strong and
 * irregular verbs, not grammatically derivable, so it's stored explicitly
 * rather than computed.
 */
export const verbsV1: SeedVerb[] = [
  { infinitive: 'sein', past_tense: 'war', english: 'to be', level: 'A1' },
  { infinitive: 'haben', past_tense: 'hatte', english: 'to have', level: 'A1' },
  { infinitive: 'werden', past_tense: 'wurde', english: 'to become', level: 'A1' },
  { infinitive: 'können', past_tense: 'konnte', english: 'to be able to / can', level: 'A1' },
  { infinitive: 'müssen', past_tense: 'musste', english: 'to have to / must', level: 'A1' },
  { infinitive: 'wollen', past_tense: 'wollte', english: 'to want', level: 'A1' },
  { infinitive: 'sollen', past_tense: 'sollte', english: 'to be supposed to', level: 'A1' },
  { infinitive: 'dürfen', past_tense: 'durfte', english: 'to be allowed to', level: 'A1' },
  { infinitive: 'mögen', past_tense: 'mochte', english: 'to like', level: 'A1' },
  { infinitive: 'gehen', past_tense: 'ging', english: 'to go', level: 'A1' },
  { infinitive: 'kommen', past_tense: 'kam', english: 'to come', level: 'A1' },
  { infinitive: 'machen', past_tense: 'machte', english: 'to make / do', level: 'A1' },
  { infinitive: 'sagen', past_tense: 'sagte', english: 'to say', level: 'A1' },
  { infinitive: 'sehen', past_tense: 'sah', english: 'to see', level: 'A1' },
  { infinitive: 'geben', past_tense: 'gab', english: 'to give', level: 'A1' },
  { infinitive: 'nehmen', past_tense: 'nahm', english: 'to take', level: 'A1' },
  { infinitive: 'finden', past_tense: 'fand', english: 'to find', level: 'A1' },
  { infinitive: 'wissen', past_tense: 'wusste', english: 'to know (a fact)', level: 'A1' },
  { infinitive: 'denken', past_tense: 'dachte', english: 'to think', level: 'A1' },
  { infinitive: 'bringen', past_tense: 'brachte', english: 'to bring', level: 'A1' },
  { infinitive: 'kennen', past_tense: 'kannte', english: 'to know (a person/place)', level: 'A1' },
  { infinitive: 'stehen', past_tense: 'stand', english: 'to stand', level: 'A1' },
  { infinitive: 'sitzen', past_tense: 'saß', english: 'to sit', level: 'A1' },
  { infinitive: 'liegen', past_tense: 'lag', english: 'to lie (be positioned)', level: 'A1' },
  { infinitive: 'bleiben', past_tense: 'blieb', english: 'to stay', level: 'A1' },
  { infinitive: 'fahren', past_tense: 'fuhr', english: 'to drive / travel', level: 'A1' },
  { infinitive: 'laufen', past_tense: 'lief', english: 'to run / walk', level: 'A1' },
  { infinitive: 'fliegen', past_tense: 'flog', english: 'to fly', level: 'A2' },
  { infinitive: 'schreiben', past_tense: 'schrieb', english: 'to write', level: 'A1' },
  { infinitive: 'lesen', past_tense: 'las', english: 'to read', level: 'A1' },
  { infinitive: 'sprechen', past_tense: 'sprach', english: 'to speak', level: 'A1' },
  { infinitive: 'essen', past_tense: 'aß', english: 'to eat', level: 'A1' },
  { infinitive: 'trinken', past_tense: 'trank', english: 'to drink', level: 'A1' },
  { infinitive: 'schlafen', past_tense: 'schlief', english: 'to sleep', level: 'A1' },
  { infinitive: 'arbeiten', past_tense: 'arbeitete', english: 'to work', level: 'A1' },
  { infinitive: 'spielen', past_tense: 'spielte', english: 'to play', level: 'A1' },
  { infinitive: 'lernen', past_tense: 'lernte', english: 'to learn', level: 'A1' },
  { infinitive: 'wohnen', past_tense: 'wohnte', english: 'to live (reside)', level: 'A1' },
  { infinitive: 'leben', past_tense: 'lebte', english: 'to live (be alive)', level: 'A1' },
  { infinitive: 'kaufen', past_tense: 'kaufte', english: 'to buy', level: 'A1' },
  { infinitive: 'verkaufen', past_tense: 'verkaufte', english: 'to sell', level: 'A2' },
  { infinitive: 'brauchen', past_tense: 'brauchte', english: 'to need', level: 'A1' },
  { infinitive: 'suchen', past_tense: 'suchte', english: 'to search', level: 'A1' },
  { infinitive: 'fragen', past_tense: 'fragte', english: 'to ask', level: 'A1' },
  { infinitive: 'antworten', past_tense: 'antwortete', english: 'to answer', level: 'A1' },
  { infinitive: 'hören', past_tense: 'hörte', english: 'to hear', level: 'A1' },
  { infinitive: 'helfen', past_tense: 'half', english: 'to help', level: 'A1' },
  { infinitive: 'lieben', past_tense: 'liebte', english: 'to love', level: 'A1' },
  { infinitive: 'beginnen', past_tense: 'begann', english: 'to begin', level: 'A2' },
  { infinitive: 'öffnen', past_tense: 'öffnete', english: 'to open', level: 'A1' },
  { infinitive: 'schließen', past_tense: 'schloss', english: 'to close', level: 'A2' },
  { infinitive: 'aufstehen', past_tense: 'stand auf', english: 'to get up', is_separable: true, level: 'A1' },
  { infinitive: 'anrufen', past_tense: 'rief an', english: 'to call (phone)', is_separable: true, level: 'A1' },
  { infinitive: 'einkaufen', past_tense: 'kaufte ein', english: 'to shop', is_separable: true, level: 'A1' },
  { infinitive: 'ankommen', past_tense: 'kam an', english: 'to arrive', is_separable: true, level: 'A2' },
  { infinitive: 'anfangen', past_tense: 'fing an', english: 'to start', is_separable: true, level: 'A2' },
  { infinitive: 'mitkommen', past_tense: 'kam mit', english: 'to come along', is_separable: true, level: 'A2' },
];
